<?php
    function titre($content,$sousTitres='',$level=1) {
        echo "<h$level>$content</h$level>";
        if ($sousTitres!=''){
            echo "<p class='sub-title'>$sousTitres</p>";
        }
    }
    const IPSUM=[
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas diam nunc, lobortis eu enim in, rhoncus placerat lacus. Integer non augue eu erat lobortis gravida suscipit et magna. Donec gravida feugiat fermentum. Quisque magna erat, tristique eget cursus ac, tristique efficitur libero. Vestibulum tincidunt tincidunt erat. Aliquam erat volutpat. Nunc dignissim non urna at tincidunt.

        Nulla pellentesque fermentum sapien non sodales. Curabitur sed elit sed dolor consequat lobortis feugiat ut odio. Nulla scelerisque, diam nec aliquam blandit, diam nisl aliquam lectus, id fermentum lacus nisi aliquet erat. Phasellus pulvinar imperdiet massa. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur quis quam a dui convallis tincidunt. Vivamus est nisl, tincidunt non eros nec, dapibus porttitor mi. Proin eget porttitor metus. Duis vel dapibus tellus, eget lobortis nisi. Praesent condimentum, mauris et lacinia hendrerit, dolor ipsum lacinia sapien, a iaculis ligula enim eget justo.
        
        Aenean facilisis quam libero, sed sodales ipsum tempus vel. Praesent quis ullamcorper nisi, a facilisis augue. Nullam in libero viverra, ullamcorper eros id, dapibus felis. Duis rhoncus porta purus, mollis egestas augue congue quis. Cras placerat bibendum porta. Vestibulum congue dignissim ullamcorper. Curabitur purus dui, sagittis et libero nec, venenatis fringilla massa. Ut posuere sagittis magna et rhoncus. Donec commodo, neque id feugiat tincidunt, metus urna feugiat metus, non eleifend mauris tortor et ex. Integer ultricies commodo rhoncus. Ut feugiat ligula justo, vitae laoreet felis vehicula at. Integer vel augue at ex semper congue. Donec placerat nunc eu mi euismod dictum. Morbi iaculis lacus id nisl vulputate semper. Nam dignissim sit amet nunc ac tristique.
        
        Donec faucibus mauris hendrerit, congue nibh quis, volutpat magna. Praesent ac commodo dui. Nunc sit amet neque non ipsum scelerisque elementum. Integer cursus lorem metus, nec aliquam diam imperdiet et. Praesent quis placerat nisl. Donec vitae vehicula risus, eu dictum tellus. Suspendisse venenatis massa massa, in venenatis nulla facilisis a.
        
        Mauris a placerat nibh. Morbi gravida ultricies nibh sit amet cursus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lobortis hendrerit libero porttitor ultrices. Nunc sodales, arcu sed rutrum consectetur, ipsum nisi consequat quam, eu interdum erat nisi aliquam ex. Mauris tristique pulvinar eros at luctus. Sed in egestas sapien. Sed cursus maximus elit ac aliquet. Etiam urna mi, iaculis in purus a, laoreet viverra enim. Phasellus vehicula vehicula blandit. Curabitur a rhoncus lacus. Etiam a pretium dolor, non egestas elit. Morbi et ex accumsan diam suscipit efficitur. Quisque sit amet sollicitudin ex, vel ullamcorper nunc. Maecenas in consequat lectus, varius vulputate quam.
        
        Fusce volutpat sem a rutrum porttitor. Proin blandit orci a lorem luctus sollicitudin. Phasellus velit eros, facilisis ut suscipit in, consequat ac augue. Suspendisse auctor mi a dictum aliquet. Mauris quis fringilla nisi. Suspendisse aliquet mauris vitae consectetur dapibus. Sed consequat, lectus ut efficitur vulputate, ex nisi tincidunt massa, eget volutpat massa lacus eu mauris. Sed sed pulvinar ipsum.
        
        In aliquet justo ac est ullamcorper posuere. Ut ut malesuada nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et ultricies neque, et imperdiet tortor. Curabitur accumsan dignissim ipsum, at dictum odio tempor at. Pellentesque eget sem eu elit malesuada mollis. Etiam nunc tellus, luctus ac convallis vel, euismod sed mi. Sed eget fringilla arcu. Nullam ornare ut enim eu porta. Proin quam nisl, iaculis a commodo id, tempor sit amet sapien. Vivamus elementum erat non pharetra consectetur. Nulla consectetur porttitor lacus. Aliquam vitae tempor metus. Nulla venenatis, libero a posuere lobortis, nisl leo tempor magna, vel tempus mi eros a lectus. Morbi pellentesque, velit vitae consectetur convallis, odio mauris imperdiet neque, nec eleifend risus justo in lectus. Sed eget auctor massa.
        
        Fusce sollicitudin enim eu fringilla viverra. Fusce feugiat eget est vel fringilla. Integer ut pulvinar sapien, sit amet porta nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce vitae finibus ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque quis lacinia erat, et suscipit nulla. Suspendisse euismod ante in feugiat aliquet. Etiam a vestibulum tortor. Fusce semper sem tellus, et bibendum magna cursus id. Vivamus vitae massa mi. Donec finibus sagittis tortor vitae posuere. Vestibulum velit turpis, egestas a quam dictum, molestie placerat odio. Phasellus mollis arcu mi, pulvinar luctus justo tristique in.
        
        Pellentesque aliquam sapien justo, ut molestie felis dictum ac. Quisque sed laoreet felis. Donec nec nisi massa. Proin interdum neque quis vulputate imperdiet. Donec in metus eu turpis maximus pretium eget sed ex. Donec in eros at odio blandit accumsan. Vivamus lacinia quam vitae sollicitudin feugiat. Maecenas pharetra orci ac tempus rhoncus. Cras pellentesque rutrum consectetur. Quisque euismod sodales velit, sit amet tincidunt elit. Etiam facilisis cursus malesuada. Aenean sit amet bibendum sem. Maecenas non egestas libero. Maecenas vitae nisi eu dui sollicitudin euismod. Nunc efficitur tortor leo, id ultrices lectus imperdiet vel.
        
        Aenean luctus ante ac auctor vulputate. Nunc justo turpis, tincidunt quis volutpat et, dictum ut elit. Nam at sodales tellus, nec gravida purus. Sed pretium, mi blandit pellentesque pulvinar, dolor enim dapibus mauris, a pulvinar quam arcu sodales sem. Nunc sit amet lacus dictum, efficitur massa id, molestie dolor. Nunc vel elementum ex. Mauris finibus egestas ultricies. Aliquam erat volutpat. Nam semper ligula vitae quam tempus, id venenatis quam iaculis.
        
        In dui nulla, volutpat quis rhoncus a, dictum rutrum nibh. Donec malesuada, lorem eget gravida hendrerit, erat lorem volutpat sapien, bibendum consequat mi odio quis ligula. Pellentesque molestie purus id tellus eleifend, nec vestibulum justo dictum. Morbi feugiat, metus id posuere pharetra, diam odio dictum ex, eget ullamcorper erat orci eu neque. Aliquam vel accumsan tellus. Donec eget volutpat orci. Donec congue leo magna, et hendrerit leo ullamcorper et. Duis varius lectus a tellus sollicitudin varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        
        Maecenas sapien magna, pretium ut tristique non, efficitur vitae arcu. Fusce id nulla eu arcu egestas iaculis. Cras ultricies sapien vel elementum aliquet. Donec ornare orci eget turpis pellentesque, ut porttitor enim ultricies. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed vestibulum, ligula non luctus pretium, neque eros tincidunt justo, sit amet consectetur ligula urna sed orci. Mauris rhoncus metus vitae neque semper ultricies. Integer viverra viverra massa, sed gravida tortor mattis eget. Pellentesque auctor laoreet metus, non consequat purus ultricies quis. Donec nec tempor dolor. Maecenas fringilla arcu cursus urna convallis, quis varius dui aliquam. Praesent et dolor ut elit tempor varius a in lacus. Ut bibendum maximus erat.
        
        Etiam ut massa lorem. Vivamus sagittis finibus dolor quis finibus. Maecenas libero nunc, malesuada vel risus interdum, venenatis iaculis lacus. Suspendisse lectus dui, accumsan sed dui nec, volutpat posuere est. Integer vel lacinia odio, sit amet congue est. Vestibulum nec tempor nisi, et sodales risus. Sed lacinia hendrerit massa eu euismod. Sed cursus ex quis elit consectetur, et vestibulum sapien molestie. Aenean feugiat condimentum lorem non volutpat. Duis eu diam et tellus volutpat mattis eget ut quam. Proin volutpat consectetur sapien, nec scelerisque nunc bibendum eu. Maecenas viverra dui lorem, at luctus sem lobortis id.
        
        Integer lacus libero, vehicula at enim ullamcorper, ultrices venenatis lectus. Phasellus id tortor id mi consequat lacinia a id turpis. Ut aliquet venenatis fringilla. Etiam ultrices, elit nec feugiat congue, nisl purus dictum neque, at cursus dui dui ut justo. Aliquam in bibendum ligula. Nullam ac velit molestie, ullamcorper augue suscipit, mollis nibh. Mauris imperdiet nisi faucibus ligula dictum porttitor. In blandit urna quis erat luctus interdum. Sed hendrerit ut sem id bibendum. Aenean vel ornare massa, sit amet iaculis magna. In aliquet leo id felis condimentum tempor.
        
        Nunc in porta ante. Curabitur mi turpis, venenatis sit amet nisi at, sodales lobortis arcu. Sed vel venenatis ligula. Suspendisse potenti. Vestibulum accumsan tristique ligula. Cras cursus imperdiet risus, sed elementum neque rhoncus sed. Maecenas consequat sit amet lectus id aliquam. Etiam accumsan tincidunt neque sit amet ultrices.
        
        Aliquam erat volutpat. Maecenas urna nibh, rhoncus et felis a, gravida dapibus lorem. In justo ex, pulvinar efficitur tincidunt nec, varius ut dui. Mauris congue sapien at purus auctor, mollis mattis quam mollis. Praesent diam velit, sollicitudin volutpat tristique sed, sollicitudin et magna. Vivamus feugiat commodo fermentum. Mauris pulvinar rhoncus nisi, placerat varius sapien fringilla at. Donec lacinia sollicitudin dui in ullamcorper. Nulla facilisi. Nunc tincidunt, nunc sed maximus sodales, risus urna malesuada sem, sed bibendum purus est sit amet lorem. Morbi facilisis purus et risus porta accumsan ut eu orci. Nulla porttitor justo eros, vel interdum justo faucibus ut. Aenean sit amet mollis tortor.
        
        Suspendisse potenti. Etiam pellentesque suscipit tellus, id euismod massa laoreet in. Pellentesque eu lectus eu ex egestas ornare eu sit amet justo. Aliquam volutpat accumsan leo nec iaculis. Ut vel ipsum consequat, porta nisi non, laoreet quam. Donec convallis, tortor at vulputate pellentesque, mi elit faucibus eros, et molestie urna odio nec turpis. Suspendisse maximus neque diam, in cursus massa congue in. Mauris laoreet dolor nec aliquam commodo. Morbi eu tortor dui. In consectetur egestas ipsum in commodo.
        
        Fusce nec mauris ac nisl auctor tincidunt sit amet iaculis ligula. Cras facilisis odio vel facilisis placerat. Sed sit amet lobortis lectus. Integer egestas quis dui at dignissim. Nullam porttitor ligula et quam elementum viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec risus sapien, dapibus et dapibus eu, faucibus eget mauris. Etiam erat orci, dignissim ut tortor interdum, blandit consectetur purus. Mauris rhoncus consectetur arcu, et pretium libero. Nulla tincidunt augue sed nisi dignissim, eu rutrum lacus elementum. Aenean laoreet tortor sapien, vitae imperdiet nisl molestie at. Fusce posuere hendrerit lacinia. Nunc ut justo tincidunt, blandit nulla eget, porttitor dui. Quisque massa turpis, imperdiet non leo vestibulum, volutpat placerat enim. Fusce in pulvinar dolor, sit amet gravida urna. Vivamus elit nisi, viverra at arcu quis, aliquet eleifend ante.
        
        Nulla bibendum gravida lacus. Pellentesque et velit vitae erat iaculis pellentesque a at lorem. Aenean in finibus mi, at congue nunc. Ut egestas augue a elit pretium, quis dictum mi consectetur. Sed mauris magna, rhoncus id iaculis et, aliquam in ligula. Curabitur imperdiet vehicula diam, id suscipit dolor rhoncus sit amet. Vivamus aliquam suscipit tortor, a semper orci pulvinar vitae. Phasellus fermentum iaculis nunc vel tincidunt. Aliquam iaculis vestibulum feugiat. Vivamus non rhoncus risus. Nam at volutpat libero.
        
        Curabitur pharetra turpis a augue ultrices mollis. Aliquam leo leo, sollicitudin ultricies iaculis eu, varius vel magna. Pellentesque semper, eros et dapibus eleifend, magna lorem tempor quam, et dapibus magna lectus aliquet elit. Vestibulum lacus nisl, auctor a faucibus in, porta vel orci. Donec accumsan risus non nisi fermentum pretium. Duis pretium tristique felis vitae venenatis. Integer eleifend turpis dui, a facilisis velit ullamcorper in. Interdum et malesuada fames ac ante ipsum primis in faucibus."
    ];
?>